// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v3.21.12
// source: user.proto

package user

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	UserService_GetUserCurrent_FullMethodName = "/UserService/GetUserCurrent"
	UserService_GetUserInfo_FullMethodName    = "/UserService/GetUserInfo"
	UserService_GetIsConcern_FullMethodName   = "/UserService/GetIsConcern"
	UserService_GetUserConcern_FullMethodName = "/UserService/GetUserConcern"
	UserService_GetUserFriend_FullMethodName  = "/UserService/GetUserFriend"
)

// UserServiceClient is the client API for UserService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type UserServiceClient interface {
	GetUserCurrent(ctx context.Context, in *UserCurrentRequest, opts ...grpc.CallOption) (*UserCurrentResponse, error)
	GetUserInfo(ctx context.Context, in *UserInfoRequest, opts ...grpc.CallOption) (*UserCurrentResponse, error)
	GetIsConcern(ctx context.Context, in *GetIsConcernRequest, opts ...grpc.CallOption) (*GetIsConcernResponse, error)
	GetUserConcern(ctx context.Context, in *GetUserConcernRequest, opts ...grpc.CallOption) (*GetConcernResponse, error)
	GetUserFriend(ctx context.Context, in *GetUserFriendRequest, opts ...grpc.CallOption) (*GetFriendResponse, error)
}

type userServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewUserServiceClient(cc grpc.ClientConnInterface) UserServiceClient {
	return &userServiceClient{cc}
}

func (c *userServiceClient) GetUserCurrent(ctx context.Context, in *UserCurrentRequest, opts ...grpc.CallOption) (*UserCurrentResponse, error) {
	out := new(UserCurrentResponse)
	err := c.cc.Invoke(ctx, UserService_GetUserCurrent_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) GetUserInfo(ctx context.Context, in *UserInfoRequest, opts ...grpc.CallOption) (*UserCurrentResponse, error) {
	out := new(UserCurrentResponse)
	err := c.cc.Invoke(ctx, UserService_GetUserInfo_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) GetIsConcern(ctx context.Context, in *GetIsConcernRequest, opts ...grpc.CallOption) (*GetIsConcernResponse, error) {
	out := new(GetIsConcernResponse)
	err := c.cc.Invoke(ctx, UserService_GetIsConcern_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) GetUserConcern(ctx context.Context, in *GetUserConcernRequest, opts ...grpc.CallOption) (*GetConcernResponse, error) {
	out := new(GetConcernResponse)
	err := c.cc.Invoke(ctx, UserService_GetUserConcern_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) GetUserFriend(ctx context.Context, in *GetUserFriendRequest, opts ...grpc.CallOption) (*GetFriendResponse, error) {
	out := new(GetFriendResponse)
	err := c.cc.Invoke(ctx, UserService_GetUserFriend_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UserServiceServer is the server API for UserService service.
// All implementations must embed UnimplementedUserServiceServer
// for forward compatibility
type UserServiceServer interface {
	GetUserCurrent(context.Context, *UserCurrentRequest) (*UserCurrentResponse, error)
	GetUserInfo(context.Context, *UserInfoRequest) (*UserCurrentResponse, error)
	GetIsConcern(context.Context, *GetIsConcernRequest) (*GetIsConcernResponse, error)
	GetUserConcern(context.Context, *GetUserConcernRequest) (*GetConcernResponse, error)
	GetUserFriend(context.Context, *GetUserFriendRequest) (*GetFriendResponse, error)
	mustEmbedUnimplementedUserServiceServer()
}

// UnimplementedUserServiceServer must be embedded to have forward compatible implementations.
type UnimplementedUserServiceServer struct {
}

func (UnimplementedUserServiceServer) GetUserCurrent(context.Context, *UserCurrentRequest) (*UserCurrentResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUserCurrent not implemented")
}
func (UnimplementedUserServiceServer) GetUserInfo(context.Context, *UserInfoRequest) (*UserCurrentResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUserInfo not implemented")
}
func (UnimplementedUserServiceServer) GetIsConcern(context.Context, *GetIsConcernRequest) (*GetIsConcernResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetIsConcern not implemented")
}
func (UnimplementedUserServiceServer) GetUserConcern(context.Context, *GetUserConcernRequest) (*GetConcernResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUserConcern not implemented")
}
func (UnimplementedUserServiceServer) GetUserFriend(context.Context, *GetUserFriendRequest) (*GetFriendResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUserFriend not implemented")
}
func (UnimplementedUserServiceServer) mustEmbedUnimplementedUserServiceServer() {}

// UnsafeUserServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to UserServiceServer will
// result in compilation errors.
type UnsafeUserServiceServer interface {
	mustEmbedUnimplementedUserServiceServer()
}

func RegisterUserServiceServer(s grpc.ServiceRegistrar, srv UserServiceServer) {
	s.RegisterService(&UserService_ServiceDesc, srv)
}

func _UserService_GetUserCurrent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserCurrentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).GetUserCurrent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserService_GetUserCurrent_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).GetUserCurrent(ctx, req.(*UserCurrentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_GetUserInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).GetUserInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserService_GetUserInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).GetUserInfo(ctx, req.(*UserInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_GetIsConcern_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetIsConcernRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).GetIsConcern(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserService_GetIsConcern_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).GetIsConcern(ctx, req.(*GetIsConcernRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_GetUserConcern_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserConcernRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).GetUserConcern(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserService_GetUserConcern_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).GetUserConcern(ctx, req.(*GetUserConcernRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_GetUserFriend_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserFriendRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).GetUserFriend(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserService_GetUserFriend_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).GetUserFriend(ctx, req.(*GetUserFriendRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// UserService_ServiceDesc is the grpc.ServiceDesc for UserService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var UserService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "UserService",
	HandlerType: (*UserServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetUserCurrent",
			Handler:    _UserService_GetUserCurrent_Handler,
		},
		{
			MethodName: "GetUserInfo",
			Handler:    _UserService_GetUserInfo_Handler,
		},
		{
			MethodName: "GetIsConcern",
			Handler:    _UserService_GetIsConcern_Handler,
		},
		{
			MethodName: "GetUserConcern",
			Handler:    _UserService_GetUserConcern_Handler,
		},
		{
			MethodName: "GetUserFriend",
			Handler:    _UserService_GetUserFriend_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "user.proto",
}
