// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v3.21.12
// source: fly.proto

package fly

import (
	grpc "google.golang.org/grpc"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const ()

// FlyServiceClient is the client API for FlyService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type FlyServiceClient interface {
}

type flyServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewFlyServiceClient(cc grpc.ClientConnInterface) FlyServiceClient {
	return &flyServiceClient{cc}
}

// FlyServiceServer is the server API for FlyService service.
// All implementations must embed UnimplementedFlyServiceServer
// for forward compatibility
type FlyServiceServer interface {
	mustEmbedUnimplementedFlyServiceServer()
}

// UnimplementedFlyServiceServer must be embedded to have forward compatible implementations.
type UnimplementedFlyServiceServer struct {
}

func (UnimplementedFlyServiceServer) mustEmbedUnimplementedFlyServiceServer() {}

// UnsafeFlyServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to FlyServiceServer will
// result in compilation errors.
type UnsafeFlyServiceServer interface {
	mustEmbedUnimplementedFlyServiceServer()
}

func RegisterFlyServiceServer(s grpc.ServiceRegistrar, srv FlyServiceServer) {
	s.RegisterService(&FlyService_ServiceDesc, srv)
}

// FlyService_ServiceDesc is the grpc.ServiceDesc for FlyService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var FlyService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "FlyService",
	HandlerType: (*FlyServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams:     []grpc.StreamDesc{},
	Metadata:    "fly.proto",
}
